In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [15]:
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9611111111111111

In [16]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)  

0.9851851851851852

In [17]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9722222222222222

In [19]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [20]:
for train_index, test_index in kf.split((1,2,3,4,5,6,7,8,9)):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [21]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [25]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [31]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
   X_train, X_test, y_train, y_test =  digits.data[train_index], digits.data[test_index],\
    digits.target[train_index],digits.target[test_index]

   scores_l.append(get_score(LogisticRegression(max_iter=1000),X_train, X_test, y_train, y_test))
   scores_svm.append(get_score(SVC(),X_train, X_test, y_train, y_test))
   scores_rf.append(get_score(RandomForestClassifier(),X_train, X_test, y_train, y_test))
     


     

  

   
   



In [36]:
scores_l

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [37]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [38]:
scores_rf

[0.9365609348914858, 0.9549248747913188, 0.9265442404006677]

In [39]:
from sklearn.model_selection import cross_val_score

In [43]:
cross_val_score(LogisticRegression(max_iter=1000),digits.data,digits.target,cv=3)

array([0.91986644, 0.94156928, 0.91652755])

In [45]:
cross_val_score(SVC(),digits.data,digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [46]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3)

array([0.93322204, 0.95325543, 0.92487479])